name:                note
version:             0.1.0.0
git:                 "https://bitbucket.org/HelloKitty8/hs-note"
license:             BSD3
author:              "Keane Yahn-Krafft"
maintainer:          "thisaintforuruse@gmail.com"
copyright:           "2018 Keane Yahn-Krafft"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/note#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- cryptonite
- bytestring
- bytestring-conversion
- text
- memory
- mtl
- transformers
- raw-strings-qq
- byteable
- trifecta
- network
- split
- aeson
- binary
- network-socket-options
- tostring
- base64-bytestring
- unix
- either
library:
  source-dirs: 
      - src
      - src/vmap
      - src/link
  exposed-modules:
      - Link
      - Lib
      - Val
      - VMap
      - Select
      - Helpers
      - UI.Vi
      - UI.Service
      - Note
      - Abbrev
      - Parse
      - Note.Trans
  other-modules:

executables:
  note-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
        - note
  note-cli:
    main:                Main.hs
    source-dirs:         app/cli
    dependencies:
        - note
        - aeson

tests:
  note-test:
    main:                Spec.hs
    source-dirs:         
    - test
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - note
    - QuickCheck
    - checkers
